---
- name: Deploy Apache on EC2 Web Servers
  hosts: Web_Servers
  become: true
  tasks:
  - name: Install apache is at the latest version
    ansible.builtin.yum:
      name: httpd
      state: latest      